name: UltimateWarpPad
version: '${version}'
main: org.nguyendevs.ultimateWarpPad.UltimateWarpPad
api-version: '1.21'
load: POSTWORLD

depend: [WorldGuard]
softdepend: [Vault]

commands:
  wpa:
    description: Admin Warp Pad commands
    usage: /wpa <reload|create|delete|setting|give|fixall|info>
    permission: uwp.admin
  wpp:
    description: Player Warp Pad commands
    usage: /wpp <create|delete|setting|trust>

permissions:
  uwp.use:
    description: Use any warp pad
    default: true
  uwp.admin:
    description: Admin warp commands
    default: op
  uwp.user.create:
    description: Create personal warps
    default: true
  uwp.user.delete:
    description: Delete personal warps
    default: true
  uwp.user.setting:
    description: Open warp settings
    default: true
  uwp.user.trust:
    description: Trust other players on your warps
    default: true
  uwp.craft:
    description: Permission to use the Warp Creator item to create a warp
    default: op
  uwp.user.create.<n>:
    description: Override max warps per player. Replace <n> with a number.
    default: false
  uwp.user.range.<n>:
    description: Add a custom range option to the range cycle. Replace <n> with a number.
    default: false
